# Generated by Django 3.1.1 on 2020-09-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_component', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DrugUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_use', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "drug's mode of use",
                'verbose_name_plural': "drugs' mode of use",
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('active_component', models.ManyToManyField(to='drug_database.ActiveComponent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_database.company')),
            ],
        ),
        migrations.CreateModel(
            name='SheepDrugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=10)),
                ('colour', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SheepPathogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SheepDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_elements', models.CharField(blank=True, max_length=50)),
                ('meat_withdrawl_period', models.IntegerField()),
                ('mode_of_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_database.druguse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_database.product')),
                ('target_pathogens', models.ManyToManyField(to='drug_database.SheepPathogen')),
                ('type', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='drug_database.sheepdrugtype')),
            ],
        ),
    ]
