name: heroku deployment
on:
  workflow_run:
    workflows: ["tests"]
    branches: [master]
    types:
      - completed
      - requested
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2 # default checkout action for workflows
      - name: push_to_heroku_main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/scops-antihelmintics.git origin/master:master
